# Generated by Django 5.2.11 on 2026-02-09 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('gst', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number')),
                ('logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='client_headers/')),
                ('quotation_footer_image', models.ImageField(blank=True, null=True, upload_to='client_footers/')),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_data',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='followup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('converted_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'followup_table',
            },
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.client_data')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.client_data')),
            ],
        ),
        migrations.CreateModel(
            name='followupremark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('remark_date', models.DateField(default=django.utils.timezone.now)),
                ('remark_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='lead_app.followup_table')),
            ],
            options={
                'db_table': 'followupremark',
            },
        ),
        migrations.CreateModel(
            name='leadsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.client_data')),
            ],
            options={
                'verbose_name': 'lead Source',
                'verbose_name_plural': 'lead Sources',
                'db_table': 'leadsource',
            },
        ),
        migrations.CreateModel(
            name='leads_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category', models.CharField(max_length=100)),
                ('requirement_details', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assign_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead_app.client_data')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lead_app.employee')),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.leadsource')),
            ],
            options={
                'db_table': 'leads_table',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_type', models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST')], max_length=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lead_app.client_data')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.CharField(blank=True, max_length=100)),
                ('client_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_type', models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST')], max_length=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_upto', models.DateField(blank=True)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=80, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.client_data')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead_app.leads_table')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lead_app.employee')),
            ],
            options={
                'db_table': 'quotation',
            },
        ),
        migrations.CreateModel(
            name='quotationitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lead_app.quotation')),
            ],
            options={
                'db_table': 'quotationitem',
            },
        ),
        migrations.CreateModel(
            name='terms_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='lead_app.client_data')),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
                'db_table': 'terms_conditions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='enquiryfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_categories', to='lead_app.client_data')),
            ],
            options={
                'verbose_name': 'Enquiry Category',
                'verbose_name_plural': 'Enquiry Categories',
                'db_table': 'enquiryfor',
                'unique_together': {('client', 'name')},
            },
        ),
    ]
