# Generated by Django 5.2.11 on 2026-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryfor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
