# Generated by Django 5.2.11 on 2026-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0002_alter_enquiryfor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='spec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
