# Generated by Django 5.2.11 on 2026-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0003_quotationitem_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
