# Generated by Django 5.2.9 on 2025-12-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category', models.CharField(max_length=100)),
                ('lead_source', models.CharField(max_length=100)),
                ('requirement_details', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assign_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead_app.client')),
            ],
            options={
                'db_table': 'Lead_table',
            },
        ),
    ]
