# Generated by Django 5.2.11 on 2026-07-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0005_company_alter_enquiry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
