# Generated by Django 5.2.9 on 2025-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0008_leadsource_status_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
