# Generated by Django 5.2.9 on 2025-12-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0009_alter_leadsource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_categories', to='lead_app.client')),
            ],
            options={
                'verbose_name': 'Enquiry Category',
                'verbose_name_plural': 'Enquiry Categories',
                'db_table': 'EnquiryFor',
                'unique_together': {('client', 'name')},
            },
        ),
    ]
