# Generated by Django 5.2.9 on 2025-12-29 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0012_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2025, 12, 29, 17, 9, 50, 235965)),
        ),
    ]
