# Generated by Django 5.2.9 on 2025-12-30 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0014_quotation_cgst_quotation_igst_quotation_sgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2025, 12, 30, 15, 47, 27, 683678)),
        ),
    ]
