# Generated by Django 5.2.9 on 2026-01-03 12:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0016_quotation_version_alter_quotation_valid_upto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('converted_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 12, 49, 27, 359114)),
        ),
        migrations.CreateModel(
            name='FollowUpRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('remark_date', models.DateField(default=datetime.datetime(2026, 1, 3, 12, 49, 27, 359114))),
                ('remark_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 1, 3, 12, 49, 27, 359114))),
                ('followup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='lead_app.followup')),
            ],
        ),
    ]
