# Generated by Django 5.2.9 on 2026-01-05 09:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0017_followup_alter_quotation_valid_upto_followupremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupremark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 9, 47, 33, 902315)),
        ),
        migrations.AlterField(
            model_name='followupremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 9, 47, 33, 902315)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 9, 47, 33, 899317)),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
