# Generated by Django 5.2.9 on 2026-01-05 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0018_alter_followupremark_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupremark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 10, 2, 49, 119873)),
        ),
        migrations.AlterField(
            model_name='followupremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 10, 2, 49, 119873)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 10, 2, 49, 119873)),
        ),
    ]
