# Generated by Django 5.2.9 on 2026-01-05 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0019_document_expiry_date_alter_followupremark_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupremark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 10, 4, 55, 472319)),
        ),
        migrations.AlterField(
            model_name='followupremark',
            name='remark_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 10, 4, 55, 472319)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2026, 1, 5, 10, 4, 55, 472319)),
        ),
    ]
