# Generated by Django 5.2.9 on 2026-01-05 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0022_alter_followupremark_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupremark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='followupremark',
            name='remark_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
