# Generated by Django 5.2.9 on 2026-01-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0024_client_header_image_client_quotation_footer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='quotation_footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_footers/'),
        ),
    ]
