# Generated by Django 5.2.9 on 2026-01-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0029_remove_privacypolicy_updated_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPolicy',
            new_name='terms_conditions',
        ),
    ]
