# Generated by Django 5.2.9 on 2026-01-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0030_rename_privacypolicy_terms_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms_conditions',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterField(
            model_name='terms_conditions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='lead_app.client'),
        ),
        migrations.AlterModelTable(
            name='terms_conditions',
            table='terms_conditions',
        ),
    ]
