# Generated by Django 5.2.9 on 2026-01-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0032_alter_document_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
        migrations.AlterModelTable(
            name='followup',
            table='FollowUp',
        ),
        migrations.AlterModelTable(
            name='followupremark',
            table='FollowUpRemark',
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='Quotation',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='QuotationItem',
        ),
    ]
