# Generated by Django 5.2.9 on 2026-01-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0034_alter_client_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lead_app.employee'),
        ),
    ]
