# Generated by Django 5.2.11 on 2026-02-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0040_alter_product_options_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='leads',
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'verbose_name': 'lead Source', 'verbose_name_plural': 'lead Sources'},
        ),
    ]
