# Generated by Django 5.2.11 on 2026-02-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0041_rename_lead_leads_alter_leadsource_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='client_data',
        ),
        migrations.AlterModelOptions(
            name='client_data',
            options={},
        ),
        migrations.AlterModelTable(
            name='client_data',
            table='client_data',
        ),
    ]
