# Generated by Django 5.2.11 on 2026-02-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0042_rename_client_client_data_alter_client_data_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
