# Generated by Django 5.2.11 on 2026-02-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0043_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leads',
            new_name='leads_table',
        ),
        migrations.AlterModelTable(
            name='leads_table',
            table='leads_table',
        ),
    ]
