# Generated by Django 5.2.11 on 2026-02-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0044_rename_leads_leads_table_alter_leads_table_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowUp',
            new_name='followup_table',
        ),
        migrations.AlterModelTable(
            name='followup_table',
            table='followup_table',
        ),
    ]
