# Generated by Django 5.2.8 on 2026-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0045_rename_followup_followup_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryfor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
