# Generated by Django 5.2.11 on 2026-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0046_alter_enquiryfor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
