# Generated by Django 5.2.11 on 2026-03-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0047_client_data_last_logout_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='spec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
