# Generated by Django 5.2.9 on 2025-12-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0002_leadsource'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leadsource',
            table='LeadSource',
        ),
    ]
