# Generated by Django 5.2.9 on 2025-12-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0005_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.leadsource'),
        ),
    ]
