# Generated by Django 5.2.9 on 2025-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0006_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
