# Generated by Django 5.2.9 on 2025-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0007_employee_password_alter_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
