# Generated by Django 5.2.9 on 2025-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0010_enquiryfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryfor',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
