# Generated by Django 5.2.9 on 2025-12-31 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0015_quotation_quotation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_upto',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 12, 46, 0, 834977)),
        ),
    ]
