# Generated by Django 5.2.9 on 2026-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0023_alter_followupremark_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_headers/'),
        ),
        migrations.AddField(
            model_name='client',
            name='quotation_footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='client_quotations/'),
        ),
    ]
