# Generated by Django 5.2.9 on 2026-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0025_alter_client_quotation_footer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
