# Generated by Django 5.2.9 on 2026-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0026_quotationitem_description_quotationitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
