# Generated by Django 5.2.9 on 2026-01-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0028_privacypolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='updated_by',
        ),
    ]
