# Generated by Django 5.2.9 on 2026-01-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0031_alter_terms_conditions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
    ]
