# Generated by Django 5.2.9 on 2026-01-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0033_alter_document_table_alter_followup_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
