# Generated by Django 5.2.9 on 2026-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0037_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='converted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
