# Generated by Django 5.2.11 on 2026-02-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0039_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='enquiryfor',
            table='enquiryfor',
        ),
        migrations.AlterModelTable(
            name='followup',
            table='followup',
        ),
        migrations.AlterModelTable(
            name='followupremark',
            table='followupremark',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='lead',
        ),
        migrations.AlterModelTable(
            name='leadsource',
            table='leadsource',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='quotation',
            table='quotation',
        ),
        migrations.AlterModelTable(
            name='quotationitem',
            table='quotationitem',
        ),
    ]
