# Generated by Django 5.2.11 on 2026-06-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0048_quotationitem_spec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
