# Generated by Django 5.2.11 on 2026-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_app', '0050_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
